language: php
php:
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    

before_install:
    - sudo apt-get update
    - sudo apt-get install libzbar0 libzbar-dev imagemagick
script:
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - phpize
    - ./configure
    - make
    - make test
